# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: api.proto for package 'api'

require 'grpc'
require 'api_pb'

module Api
  module UserPosts
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'api.UserPosts'

      rpc :GetPost, ::Api::PostId, ::Api::Post
      rpc :GetPosts, ::Api::Request, stream(::Api::Post)
      rpc :GetBestPost, stream(::Api::PostId), ::Api::Post
      rpc :GetPostsByIds, stream(::Api::PostId), stream(::Api::Post)
    end

    Stub = Service.rpc_stub_class
  end
end
