# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("api.proto", :syntax => :proto3) do
    add_message "api.Request" do
      optional :limit, :int32, 1
    end
    add_message "api.Post" do
      optional :user, :message, 1, "api.User"
      optional :title, :string, 3
      optional :text, :string, 4
    end
    add_message "api.User" do
      optional :username, :string, 1
      optional :first_name, :string, 2
      optional :last_name, :string, 3
      optional :email, :string, 4
      optional :bio, :string, 5
      optional :age, :string, 6
    end
    add_message "api.PostId" do
      optional :post_id, :int32, 1
    end
  end
end

module Api
  Request = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("api.Request").msgclass
  Post = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("api.Post").msgclass
  User = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("api.User").msgclass
  PostId = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("api.PostId").msgclass
end
