# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: posts.proto for package 'posts'

require 'grpc'
require 'posts_pb'

module Posts
  module GetPosts
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'posts.GetPosts'

      rpc :ListData, ::Posts::Request, stream(::Posts::Data)
    end

    Stub = Service.rpc_stub_class
  end
end
